#!/usr/bin/env python3
"""
Script to set up dashboard service in supervisor configuration
"""
import os

def create_supervisor_config():
    """Create supervisor configuration for dashboard"""
    
    config_content = """# READONLY FILE, DO NOT EDIT THIS FILE
[program:backend]
command=/root/.venv/bin/uvicorn server:app --host 0.0.0.0 --port 8001 --workers 1 --reload
directory=/app/backend
autostart=true
autorestart=true
environment=APP_URL="https://formflow-repair.preview.emergentagent.com",INTEGRATION_PROXY_URL="https://integrations.emergentagent.com"
stderr_logfile=/var/log/supervisor/backend.err.log
stdout_logfile=/var/log/supervisor/backend.out.log
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true

[program:frontend]
command=yarn start
environment=HOST="0.0.0.0",PORT="3000",
directory=/app/website
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/frontend.err.log
stdout_logfile=/var/log/supervisor/frontend.out.log
stopsignal=TERM
stopwaitsecs=50
stopasgroup=true
killasgroup=true

[program:dashboard]
command=yarn start
environment=HOST="0.0.0.0",PORT="3001",
directory=/app/dashboard
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/dashboard.err.log
stdout_logfile=/var/log/supervisor/dashboard.out.log
stopsignal=TERM
stopwaitsecs=50
stopasgroup=true
killasgroup=true

[program:mongodb]
command=/usr/bin/mongod --bind_ip_all
autostart=true
autorestart=true
stderr_logfile=/var/log/mongodb.err.log
stdout_logfile=/var/log/mongodb.out.log

"""
    
    config_path = "/etc/supervisor/conf.d/supervisord.conf"
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print("✅ Updated supervisor configuration with dashboard service")
    print("📁 Configuration saved to:", config_path)
    
def show_service_info():
    """Show service configuration information"""
    print("\n" + "="*50)
    print("🚀 SENTRATECH SERVICES CONFIGURATION")
    print("="*50)
    print("🔧 Backend API: Port 8001")
    print("🌐 Website: Port 3000 (sentratech.net)")
    print("📊 Dashboard: Port 3001 (admin.sentratech.net)")
    print("🗄️  MongoDB: Default port")
    print("\n📋 Service Commands:")
    print("   sudo supervisorctl restart all")
    print("   sudo supervisorctl status")
    print("   sudo supervisorctl restart dashboard")
    print("="*50)

if __name__ == "__main__":
    print("🔧 Setting up SentraTech Dashboard Service...")
    
    create_supervisor_config()
    show_service_info()
    
    print("\n⚠️  To apply changes:")
    print("   sudo supervisorctl reread")
    print("   sudo supervisorctl update") 
    print("   sudo supervisorctl restart all")
    print("\n✅ Dashboard service configuration complete!")