# CoreDNS ConfigMap Update for External DNS Resolution
# Apply with: kubectl apply -f 01-coredns-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        # Forward external DNS queries to Google DNS and Cloudflare
        forward . 8.8.8.8 8.8.4.4 1.1.1.1 1.0.0.1
        cache 30
        loop
        reload
        loadbalance
    }
---
# Note: After applying this ConfigMap, restart CoreDNS:
# kubectl rollout restart deployment/coredns -n kube-system