# Deployment Restart Commands
# These commands should be run after applying the above configurations

# 1. Restart CoreDNS to pick up new configuration
kubectl rollout restart deployment/coredns -n kube-system

# 2. Wait for CoreDNS to be ready
kubectl rollout status deployment/coredns -n kube-system

# 3. Restart admin proxy deployment (update deployment name as needed)
kubectl rollout restart deployment/admin-proxy -n emergent-agents-env

# 4. Wait for admin proxy to be ready  
kubectl rollout status deployment/admin-proxy -n emergent-agents-env

# 5. Restart backend deployment if separate (update as needed)
kubectl rollout restart deployment/backend -n emergent-agents-env

# 6. Verify pods are running
kubectl get pods -n emergent-agents-env

# 7. Check ingress status
kubectl get ingress -n emergent-agents-env

# 8. Verify NetworkPolicy is applied
kubectl get networkpolicy -n emergent-agents-env

# 9. Test DNS resolution from a pod
kubectl exec -it <pod-name> -n emergent-agents-env -- nslookup api.sentratech.net

# 10. Test external connectivity
kubectl exec -it <pod-name> -n emergent-agents-env -- curl -k https://api.sentratech.net/v1/health